### ISSUE TITLE
Visual Studio 2017/2015 throw a lot of errors

### ISSUE THREAD

**Issue by shujaatak** [amhndu/fly#1]
I have followed all the required steps exactly as you have mentioned in the readme file but the compiler throw a lot of errors. Can you please compile on your side?
![capture](https://user-images.githubusercontent.com/14161646/41464699-a71f80fe-70b4-11e8-85a4-4c8a88200c46.PNG)

**Comment by shujaatak** [comment]
I found that `uint` and `not` were not recognized so I changed them to `unsigned int` and `!` now many errors have gone but I still get the following errors:
![capture](https://user-images.githubusercontent.com/14161646/41465018-caf61fdc-70b5-11e8-99a3-3a45c3a5d303.PNG)

**Comment by amhndu** [comment]
Can you confirm if this still exists with the latest commit ?
It compiles fine with g++ 8.1, I do not have have Visual Studio to confirm.

**Comment by shujaatak** [comment]
Old errors have gone but now I get these:
![capture](https://user-images.githubusercontent.com/14161646/41480979-b7dda31e-70e9-11e8-8d43-82769deccbca.PNG)

**Comment by shujaatak** [comment]
Oh the above errors were due to `uint` and `not` so again I changed them to `unsigned int` and` !` now the above errors have gone but I now I get a lot more errors :( 
![capture](https://user-images.githubusercontent.com/14161646/41481948-63fcdfc2-70ed-11e8-9027-2b15bde153da.PNG)

**Comment by shujaatak** [comment]
Well, I searched and replaced `uint` and `not` in whole project with `unsigned int` and `!` and now the project is compiling perfectly! 
![capture](https://user-images.githubusercontent.com/14161646/41482363-cca81e32-70ee-11e8-8625-c1b88bc701ac.PNG)

**Comment by shujaatak** [comment]
I also noticed that <cstdint> had no effect so I had to replace `uint` with `unsigned int `.
Thanks for this awesome project! 👍

**Comment by amhndu** [comment]
I had included the required header for uints to be recognized in a recent commit, you shouldn't be getting any errors for uint.
Thank you for reporting this, I'll fix the `not` errors as well.
Can you run `git diff` in the project source and post the output ?
