### ISSUE TITLE
Setup Travis CI for autobuild AppImage (portable package for Linux)

### ISSUE THREAD

**Issue by ghost** [amhndu/fly#2]
Lets setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

0. [x] Create `.travis.yml` in the root of active branch.
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is what resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any support ask here:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by amhndu** [comment]
I have made a simple `.travis.yml` just to test out the Travis Ci but I'm not sure if I want to spend the effort into an automated AppImage build script. I won't really be making any updates to this project so I don't see much of a point.

I do have a `BUILD_STATIC` option in CMake which I can use to produce a static binary which links all the dependencies, including libstdc++ which I can then "release"
